[package]
name = "for_tests"
version = "0.1.0"

[addresses]
Std = "0x1"
Demo = "0x2"

AptosAddress = "e514cdb65f2d8a6c56868fb6876c7431"
DiemAddress = "0xe514cdb65f2d8a6c56868fb6876c7431"
PontemAddress = "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"


[dependencies]
MoveStdlib = { local = "./move-stdlib" }
