name: Tests
on:
  push:

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v13

      - uses: cachix/cachix-action@v10
        with:
          name: pontem
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - uses: actions/checkout@v2.3.4

      - run: nix build --experimental-features "flakes nix-command"
